//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.TranslationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RedWineFacts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RedWineFacts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.TranslationResources.RedWineFacts", typeof(RedWineFacts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Bordeaux wines are broadly classified according to which bank of the Gironde estuary the wine is made. Left Bank Bordeauxs tend to be more powerful and expensive than Right Bank..
        /// </summary>
        public static string Bordeaux {
            get {
                return ResourceManager.GetString("Bordeaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chateau Margaux 1787 is perhaps the world&apos;s most expensive bottle of wine ever broken. Insured for $225,000, it was smashed at a party when a waiter accidently bumped into a table. .
        /// </summary>
        public static string ChateauMargaux1787 {
            get {
                return ResourceManager.GetString("ChateauMargaux1787", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Code of Hammurabi (1,720 BC) forbid the selling of diluted alcohol which was punishable by being thrown into water to drown..
        /// </summary>
        public static string CodeofHammurabi {
            get {
                return ResourceManager.GetString("CodeofHammurabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red wine is a good source of the antioxidant resveratrol (which helps prevent cell damage) and may be beneficial for heart health when consumed in moderation..
        /// </summary>
        public static string RedWineAntioxidants {
            get {
                return ResourceManager.GetString("RedWineAntioxidants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red wine contains at least 800 - 1000 different chemical compounds, but some of the most important when discussing wine are tannins, anthocyanins, and flavonols..
        /// </summary>
        public static string RedWineChemicals {
            get {
                return ResourceManager.GetString("RedWineChemicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ancient Roman&apos;s saw wine as a daily neccessity to be consumed by people of all social classes. It was even prescribed to cure depression and bodily ailments..
        /// </summary>
        public static string RomanWine {
            get {
                return ResourceManager.GetString("RomanWine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term &quot;Super Tuscans&quot; originated in the 1970s when winemakers in Italy were forced to break away from government (DOC) standards which restricted them from using certain grapes and techniques needed to create higher quality wines..
        /// </summary>
        public static string SuperTuscans {
            get {
                return ResourceManager.GetString("SuperTuscans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term &quot;toasting&quot; may have originated with the 16th century practice of placing toasted bread in wine to reduce acidity and improve flavour. The term eventually came to encompass the libations and honors that surrounded the beverage..
        /// </summary>
        public static string Toasting {
            get {
                return ResourceManager.GetString("Toasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most wine is ideally stored and aged at 13 °C (55 °F) with a relative humidity of 70%..
        /// </summary>
        public static string WineAgingTemp {
            get {
                return ResourceManager.GetString("WineAgingTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of wine comes from the skin (exocarp) of the grapes, not the juice. How long the skins come into contact with the must (maceration) will effect color. Interestingly, white wine can be made from red grapes if quickly pressed..
        /// </summary>
        public static string WineColor {
            get {
                return ResourceManager.GetString("WineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a 2001 study by Frédéric Brochet, wine experts were tricked into preceiving white wine as red wine, simply by dying it red..
        /// </summary>
        public static string WineTrick {
            get {
                return ResourceManager.GetString("WineTrick", resourceCulture);
            }
        }
    }
}
